### ISSUE TITLE
錄影相關事宜

### ISSUE THREAD

**Issue by TP-YEN** [compiler-s20/discussion#35]
@compiler-s20/2020-teaching-team 

Dear 助教與老師好

有關線上上課錄影事宜，

希望能提供錄影檔供寫作業與期中期末考時，可以回撥複習，

覺得對寫作業會有很大的幫助，謝謝!

(P.S. 我是有準時上線上課的同學，不過還是希望能有錄影檔做複習，這也是線上上課的優點

之一，可以在學期結束再關閉分享)

**Comment by ianre657** [comment]
相關內容可以參考 #7, #26

@ypyou 
想問老師對此事的看法

@tigercosmos 如果真的有的話可能要找你技術支援

**Comment by tigercosmos** [comment]
As far as I know, Prof. You prefers not to record lectures.
However, I agree with @TP-YEN's points.

In fact, Google Meet can directly record videos now, just click "record" on the board and it will be stored in the Google Drive. So, if You wants, he (has the permission) can record lectures for students.

**Comment by ypyou** [comment]
@compiler-s20/2020-students 

Considering many requests, I will record the lectures using Google Meet's recording feature. In case I forget to push the record button at the beginning of a lecture, anyone who notices that, please click the "record" button for me. 

For those who would like to access the recording, please fill out the following Google Forms by Thursday noon (12:00 PM on April 9): [https://forms.gle/tAqb3Bz4T8HUQPkK7](https://forms.gle/tAqb3Bz4T8HUQPkK7).

**Comment by ypyou** [comment]
@compiler-s20/2020-students 
Those who had signed up for recording access now should have the permission to watch the recording videos.

**Comment by www1800** [comment]
請問有網址嗎

**Comment by ypyou** [comment]
Haven't you received an email like this?

<img width="1175" alt="截圖 2020-04-10 上午9 54 12" src="https://user-images.githubusercontent.com/6721926/78955288-678a5180-7b11-11ea-9f63-0aec971d5fc7.png">

**Comment by LeslieFan0531** [comment]
老師~我也沒收到耶

Yi-Ping You <notifications@github.com> 於 2020年4月10日 週五 上午9:56寫道：

**Comment by ypyou** [comment]
Try to find them on your Google Drive.

<img width="250" alt="截圖 2020-04-10 上午10 05 44" src="https://user-images.githubusercontent.com/6721926/78955909-4b87af80-7b13-11ea-99dd-aabf2e17ae7e.png">

**Comment by LeslieFan0531** [comment]
有了 謝謝老師!!!

Yi-Ping You <notifications@github.com> 於 2020年4月10日 週五 上午10:09寫道：

**Comment by Eric-SA-Chen** [comment]
老師不好意思，我昨天中午12點前。
沒有在：https://forms.gle/tAqb3Bz4T8HUQPkK7
註冊權限。
現在無法看到上課錄製的視頻。

是否能請老師，再開放申請權限的時間呢？
老師抱歉，我沒有仔細看信。

**Comment by ypyou** [comment]
@compiler-s20/2020-students 

If you have not yet signed up for permission to access the recording videos, this is your last chance. The registration form ([https://forms.gle/tAqb3Bz4T8HUQPkK7](https://forms.gle/tAqb3Bz4T8HUQPkK7)) will be closed at 12:00 PM on April 13 (next Monday noon). This is firm and no other time extension will be issued. 

Please follow the rules so that I don't have to change the settings on my Google Drive over and over again.

**Comment by Eric-SA-Chen** [comment]
老師您好，請問昨天新的網址申請權限後。是否要等到禮拜一截止申請後，
才能看到影片呢？
因為申請了好幾次，但目前還是沒收到信。
且雲端硬碟也沒有共用的選項。

**Comment by ypyou** [comment]
Yes. The settings are done manually. The Google Form is just used to collect your account. That’s why I set a due date earlier.

**Comment by ypyou** [comment]
BTW, the URL is the same one, not a new one.

**Comment by ypyou** [comment]
@compiler-s20/2020-master-students 
I am considering not recording the lectures (or just share the recording videos to those who show up in the online classroom) due to low attendance rate this week. There were less than five students attended the classes this week. This is what I was concerned in the beginning of the semester when I decided to record the lectures to not. If this poor attendance rate still occurs next week, some measure will be practiced.
