### ISSUE TITLE
期中考考古題來拉

### ISSUE THREAD

**Issue by YSHsieh7777** [compiler-s20/discussion#50]
@compiler-s20/2020-students 

同學好

抱歉有點晚惹

同學可以在這裡拿到過去兩年的考古題

+ [private/past-exams](https://github.com/compiler-s20/private/tree/master/PastExams)

希望大家期中考順利 💯 

# 注意 !!!
感謝你的注意。
為了未來學弟妹的公平與幸福，請不要外流考古題。

**Comment by XiaoLeS** [comment]
不知道可不可以在這裡問考古題的問題呢?

我的問題是2018的第4題，如果我沒看錯的話，這是一個LL(2)grammar，這樣(2)要怎麼回答呢?

**Comment by ypyou** [comment]
> 不知道可不可以在這裡問考古題的問題呢?
> 
> 我的問題是2018的第4題，如果我沒看錯的話，這是一個LL(2)grammar，這樣(2)要怎麼回答呢?

1. It is not an LL(K) grammar no matter what lookahead symbols you have since it’s left recursive. Also, left factoring could help reduce the number of lookahead symbols.
2. Given a grammar, you can always construct the parse table, but there might be conflicts. In this case, if you rewrite the grammar properly, you should have the LL(1) parse table without a conflict.
